import type { MorphusTheme } from '@core/types/colors.type';
import { createTheme } from 'flowbite-react';

export const morphusTheme = createTheme<MorphusTheme>({
    colors: {
        primary: {
            baseColor: 'indigo',
            backGroundLow: 'bg-mpx-indigo-50',
            backGround: 'bg-mpx-indigo-100',
            backGroundHight: 'bg-mpx-indigo-200',
            backGroundInverse: 'bg-mpx-indigo-700',
            textOnbackGround: 'text-mpx-indigo-950',
            textOnbackGroundHight: 'text-mpx-indigo-50',
            borderOnbackGround: 'border-mpx-indigo-300',
            borderOnbackGroundHight: 'border-mpx-indigo-200',
        },
        secondary: {
            baseColor: 'sky',
            backGroundLow: 'bg-mpx-sky-50',
            backGround: 'bg-mpx-sky-100',
            backGroundHight: 'bg-mpx-sky-200',
            backGroundInverse: 'bg-mpx-sky-700',
            textOnbackGround: 'text-mpx-sky-950',
            textOnbackGroundHight: 'text-mpx-sky-50',
            borderOnbackGround: 'border-mpx-sky-300',
            borderOnbackGroundHight: 'border-mpx-sky-200',
        },
        tertiary: {
            baseColor: 'purple',
            backGroundLow: 'bg-mpx-purple-50',
            backGround: 'bg-mpx-purple-100',
            backGroundHight: 'bg-mpx-purple-200',
            backGroundInverse: 'bg-mpx-purple-700',
            textOnbackGround: 'text-mpx-purple-950',
            textOnbackGroundHight: 'text-mpx-purple-50',
            borderOnbackGround: 'border-mpx-purple-400',
            borderOnbackGroundHight: 'border-mpx-purple-200',
        },
        surface: {
            baseColor: 'zinc',
            backGroundLow: 'bg-mpx-zinc-50',
            backGround: 'bg-mpx-zinc-100',
            backGroundHight: 'bg-mpx-zinc-200',
            backGroundInverse: 'bg-mpx-zinc-700',
            textOnbackGround: 'text-mpx-zinc-950',
            textOnbackGroundHight: 'text-mpx-zinc-50',
            borderOnbackGround: 'border-mpx-zinc-300',
            borderOnbackGroundHight: 'border-mpx-zinc-200',
        },
        neutral: {
            baseColor: 'neutrau',
            backGroundLow: 'bg-mpx-neutrau-50',
            backGround: 'bg-mpx-neutrau-100',
            backGroundHight: 'bg-mpx-neutrau-200',
            backGroundInverse: 'bg-mpx-neutrau-700',
            textOnbackGround: 'text-mpx-neutrau-950',
            textOnbackGroundHight: 'text-mpx-neutrau-50',
            borderOnbackGround: 'border-mpx-zinc-300',
            borderOnbackGroundHight: 'border-mpx-zinc-200',
        },
        info: {
            baseColor: 'blue',
            backGroundLow: 'bg-mpx-blue-50',
            backGround: 'bg-mpx-blue-100',
            backGroundHight: 'bg-mpx-blue-200',
            backGroundInverse: 'bg-mpx-blue-700',
            textOnbackGround: 'text-mpx-blue-950',
            textOnbackGroundHight: 'text-mpx-blue-50',
            borderOnbackGround: 'border-mpx-slate-300',
            borderOnbackGroundHight: 'border-mpx-slate-200',
        },
        warn: {
            baseColor: 'amber',
            backGroundLow: 'bg-mpx-amber-50',
            backGround: 'bg-mpx-amber-100',
            backGroundHight: 'bg-mpx-amber-200',
            backGroundInverse: 'bg-mpx-amber-700',
            textOnbackGround: 'text-mpx-amber-950',
            textOnbackGroundHight: 'text-mpx-amber-50',
            borderOnbackGround: 'border-mpx-amber-300',
            borderOnbackGroundHight: 'border-mpx-amber-200',
        },
        success: {
            baseColor: 'green',
            backGroundLow: 'bg-mpx-green-50',
            backGround: 'bg-mpx-green-100',
            backGroundHight: 'bg-mpx-green-200',
            backGroundInverse: 'bg-mpx-green-700',
            textOnbackGround: 'text-mpx-green-950',
            textOnbackGroundHight: 'text-mpx-green-50',
            borderOnbackGround: 'border-mpx-green-300',
            borderOnbackGroundHight: 'border-mpx-green-200',
        },
        error: {
            baseColor: 'red',
            backGroundLow: 'bg-mpx-red-50',
            backGround: 'bg-mpx-red-100',
            backGroundHight: 'bg-mpx-red-200',
            backGroundInverse: 'bg-mpx-red-700',
            textOnbackGround: 'text-mpx-red-950',
            textOnbackGroundHight: 'text-mpx-red-50',
            borderOnbackGround: 'border-mpx-red-300',
            borderOnbackGroundHight: 'border-mpx-red-200',
        },
    },
});
